spring.application.name=git-sql-runner
server.port=8080

spring.datasource.url=jdbc:sqlite:meta.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.continue-on-error=true
app.sync.base-dir=D:\\Space\\java\\sql-repo\\
app.sync.sql-dir=20260320
app.driver.storage-dir=drivers

logging.level.root=INFO
logging.level.org.springframework.jdbc.core=INFO
logging.level.io.will_we.project.gitsqlrunner.application.GitSyncUseCase=INFO
logging.level.io.will_we.project.gitsqlrunner.application.SqlExecutionService=INFO
logging.level.io.will_we.project.gitsqlrunner.application.SqlScriptSupport=INFO
logging.level.io.will_we.project.gitsqlrunner.application.SqlQueryService=INFO
logging.level.io.will_we.project.gitsqlrunner.application.TargetDbConfigService=INFO
logging.level.io.will_we.project.gitsqlrunner.application.TargetDbExecutorRegistry=INFO
logging.level.io.will_we.project.gitsqlrunner.application.TargetDbConnectionSupport=INFO
logging.level.io.will_we.project.gitsqlrunner.application.DriverManagementService=INFO
logging.level.io.will_we.project.gitsqlrunner.interfaces.web.ApiExceptionHandler=INFO
logging.level.io.will_we.project.gitsqlrunner.interfaces.web.DriverManagementController=INFO
logging.level.io.will_we.project.gitsqlrunner.infrastructure.scheduler.SchedulerTasks=INFO
management.endpoints.web.exposure.include=health,info

