spring.application.name=git-sql-runner
server.port=8080

spring.datasource.url=jdbc:sqlite:meta.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
app.sync.base-dir=D:\\Space\\java\\sql-repo\\
app.sync.sql-dir=20260320

logging.level.org.springframework.jdbc.core=INFO
logging.level.com.example.gitsqlrunner.application.GitSyncUseCase=INFO
management.endpoints.web.exposure.include=health,info

