spring.application.name=git-sql-runner
server.port=8080

spring.datasource.url=jdbc:sqlite:meta.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

logging.level.org.springframework.jdbc.core=INFO
management.endpoints.web.exposure.include=health,info

